### ISSUE TITLE
[Feature Request] Enable search content

### ISSUE THREAD

**Issue by cjuroz** [lydian/plugin.video.eyny#2]
Hi (again),

Would it be possible to add a basic search option to search for content, at least, in all channels and display results. Current plugin state only allows to watch most recent videos upload (for each category)...

The idea should be to popup an input box and send text string to eyny search box (for all channels): 

![image](https://cloud.githubusercontent.com/assets/10542942/23246908/ea55aaf2-f9d1-11e6-8717-cd8686f86c73.png)

Thanks~

**Comment by lydian** [comment]
Okey, it's done!

**Comment by cjuroz** [comment]
Thank you, you are so fast implementing it. I installed the addon from your new kodi repository but when i search for any content (for example: 三國) addon will return error. See log details:

```
18:11:40 T:15168  NOTICE: URLResolver: Initializing URLResolver version: 3.0.28
18:11:46 T:15168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: int() argument must be a string or a number, not 'NoneType'
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.eyny\addon.py", line 180, in <module>
                                                gui.handle(args)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.eyny\addon.py", line 41, in handle
                                                page=int(args.get('page', 1)))
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.eyny\addon.py", line 140, in search_video
                                                if page < int(result['last_page']):
                                            TypeError: int() argument must be a string or a number, not 'NoneType'
                                            -->End of Python script error report<--
18:11:46 T:6432   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.eyny/?mode=search
18:11:46 T:6432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.eyny/?mode=search) failed
```

**Comment by lydian** [comment]
thanks for reporting. This has been fixed. (I also added tests for your case :p )

**Comment by cjuroz** [comment]
Everything is working now. Many thanks for your effort in this addon 💯
